#ifndef GUARD_CONSTANTS_BATTLE_MOVE_TYPES_H
#define GUARD_CONSTANTS_BATTLE_MOVE_TYPES_H

#define MOVE_TYPE_PHYSICAL 0
#define MOVE_TYPE_SPECIAL 1
#define MOVE_TYPE_STATUS 2

#endif  // GUARD_CONSTANTS_BATTLE_MOVE_TYPES_H
